### ISSUE TITLE
tomvanzummeren/TZStackView

### ISSUE THREAD

**Issue by pjebs** [oarrabi/OAStackView#10]
I was wondering what the difference was between this control:

https://github.com/tomvanzummeren/TZStackView

**Comment by nsomar** [comment]
Hey,

I think the main difference is that its written in swift, which means you will have to include libswiftcore.dylib and other swift libs when compiling your app.

Another main difference is in the way both project deals with changing settings, while in OAStackView performance was key (since you are going to use the stackview in complicated layouts). Changing axes and other settings will not cause the stack view to remove all the constraints.

In TZStackView changes will invalidate the constraints and add them again, this might affect performance badly for bigger, more complicated UIs.

Other differences are in the testing approaches both project uses, I have to say that testing constraint is the best approach, I will be moving the project test suite to constraints in the upcoming days.

**Comment by tomvanzummeren** [comment]
Thanks for the feedback ☺️

And sorry, I wasn't aware of this component when I created mine. I was participating WWDC when I heard about this new UIStackView and I was so enthusiastic about it that I decided to create it myself for earlier iOS versions.

But OAStackView has beaten me to the punch! I really did search for something similar when I started, but couldn't find anything!

Btw, another difference: I implemented all distribution options of the UIStackView, OAStackView did just do Fill and FillEqually. Also, just like with UIStackView, you can put subview.hidden = true inside an animation block and it will animate hiding/showing the subview. I implemented that as well with TZStackView

**Comment by harlanhaskins** [comment]
It seems like TZStackView has more features implemented, but OAStackView is faster and has more recognition.

Maybe @tomvanzummeren should contribute back to OAStackView?

**Comment by nsomar** [comment]
@tomvanzummeren and @harlanhaskins The other distribution options have been introduced today by PR https://github.com/oarrabi/OAStackView/pull/8. the readme will be updated to reflect this addition soon.

I am not sure I understand the hiding argument, but OAStackView does indeed handle hiding the views, I didn't try, but setting a subview hidden inside a beginAnimation block should animate it as I only manipulate the layout constraints.

@tomvanzummeren and @harlanhaskins  I am open to discus any contribution option guys :)

**Comment by tomvanzummeren** [comment]
Try it. Animating the hidden property of a subview doesn't just work out of the box. That's why it's mentioned in a separate part of the UIStackView docs.

But anyway, we both took different approaches. No use to contribute. OAStackView did it with performance in mind and is written in ObjC. Mine is in Swift and I decided performance is not important as you're not adding and removing subviews multiple times per second. I also can't imagine that UIStackView is doing it any differently. With TZStackView I focussed on having the exact same API and behaviour to be able to drop-in replace it with the real UIStackView and see no difference.

**Comment by tomvanzummeren** [comment]
And also:

I created TZStackView just because I wanted it for myself. This time I decided to share it with everyone by putting it on GitHub. I can take it down if it is not appreciated, but I won't contribute. It already took way too much of my spare time to create this one.

**Comment by nsomar** [comment]
@tomvanzummeren This is what happens when you hide a view inside an animation block
![369f8e6eed](https://cloud.githubusercontent.com/assets/1461052/8272550/c1bec77a-183e-11e5-96f2-137177e6ca3e.gif)

The change was to explicitly call `layoutIfNeeded` in the animation block.
I know that hidden is not animated, but OAStackView has KVO observation on the subviews, that will remove the view and rearrange the constraints accordingly.

**Comment by tomvanzummeren** [comment]
Well that's no good, is it? The red block disappears immediately. With the real UIStackView, it collapses before it disappears.

**Comment by tomvanzummeren** [comment]
This is what I mean:

![TZStackView hidden animation](https://github.com/tomvanzummeren/TZStackView/raw/master/assets/TZStackView-hide-animation.gif)

I also implemented it with KVO.

**Comment by nsomar** [comment]
@tomvanzummeren oh, now I see, thanks, I will create an issue for that

**Comment by tomvanzummeren** [comment]
Oh wow, so I am contributing after all. Happy to help!

**Comment by nsomar** [comment]
@tomvanzummeren thanks for the help :) I will close this issue and open the another one.
