### ISSUE TITLE
Is there a reason why OAStackView needs to use CATransformLayer?

### ISSUE THREAD

**Issue by izackp** [oarrabi/OAStackView#13]
```
+ (Class)layerClass {
    return [CATransformLayer class];
}
```

Its causing my logs to be spammed with a bunch of warnings:

```
<CATransformLayer: 0x7ff94dbe75a0> - changing property opaque in transform-only layer, will have no effect
```

This happens because when you load OAStackView in a xib file the coder tries to set the opaque property on the layer.

I took the code out and everything works perfectly fine.

**Comment by jamieQ** [comment]
I believe the motivation is to match the iOS 9 implementation, which uses CATransformLayer. Presumably this is a performance optimization, since the stack view is essentially just a layout container. OAStackView should override `setOpaque:` in addition to `setBackgroundColor:` to be no-ops, as the UIKit version does.

**Comment by nsomar** [comment]
Hello guys, I will be closing this issue as @garnett updated the lib to silence the log messages (Thanks @garnett  :+1: ).
